### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by saury** [ng-apimock/cypress-plugin#1]
Hi,

Firstly, very thankful to this useful mock api tool.

I found that this plugin has conflict with [ng-apimock](https://github.com/mdasberg/ng-apimock). The api calling with the incorrect request url or body.

After I migrate it to modularized `ng-apimock/core`, I found that `cy.selectScenario` has no use for changing scenario in cypress though it return 200 but nothing happens.

BTW, how did you make async/await work in cypress? AFAIK, `.then` is the only way to operate with Promise in cypress without 3rd party plugins.

**Comment by mdasberg** [comment]
@saury do you have an example that I can have a look at?

**Comment by EugeneCh** [comment]
@mdasberg can you please publish 1.0.1 version to npm?

**Comment by mdasberg** [comment]
@EugeneCh done.

**Comment by Deklin** [comment]
@mdasberg  same issue here, we see the call going to the ngapimock path but the scenario isn't changing

**Comment by Deklin** [comment]
we are using ngapimock 2.3.2 core and the 1.0.7 cypress plugin
the dev-interface ui posts this:
![image](https://user-images.githubusercontent.com/3372511/89205533-e0605e00-d585-11ea-9d04-356a014760c5.png)


the cypress plugin posts this (we picked an invalid scenario to get a dump)
![image](https://user-images.githubusercontent.com/3372511/89205563-ea825c80-d585-11ea-893a-c4c9ec2186a0.png)

**Comment by Deklin** [comment]
@mdasberg actually I think I see what is happening. the NG_API_MOCK_BASE_IDENTIFIER must scope the mock to a particular session. so what is happening is that when apimockid is passed, the UI for dev-interface shows no changes, but changes must be happening internally. So for now we are setting NG_API_MOCK_BASE_IDENTIFIER to a fake value of 'disabled' which basically bypasses this.

**Comment by mdasberg** [comment]
Your correct.

@ng-apimock/core uses a cookie `apimockId` to make sure that parallel tests don't interact with each other.
So @ng-apimock/dev-interface uses no cookie, and is used for local development. So you can run your app with mocks.

When using @ng-apimock/cypress-plugin it uses the cookie.

**Comment by Deklin** [comment]
@mdasberg thanks, So we got around it by setting the cookie to a no-op value. I'm assuming to utilize this feature properly we need to make sure our app also passes the apimockId cookie in the request to isolate it for parallel runs.
