### ISSUE TITLE
Update peer dependencies for newer major versions of Cypress

### ISSUE THREAD

**Issue by tkutcher** [ng-apimock/cypress-plugin#210]
Right now the `peerDependencies` lists

```json
  "peerDependencies": {
    "cypress": ">=4.x"
  }
```

so there is a pesky peer dependency warning if you are using a newer major version of cypress (5 or 6). From what I can tell though, none of those major upgrades in cypress touch anything this plugin deals with.

I would propose changing it to `>=4` if there are no issues.

Awesome tool - thanks so much!

**Comment by mdasberg** [comment]
@tkutcher done in version 2.1.0

**Comment by tkutcher** [comment]
@mdasberg awesome - thanks!
