### ISSUE TITLE
cy.initializeNgApimock(), why optional?

### ISSUE THREAD

**Issue by GrumpyMeow** [ng-apimock/cypress-plugin#421]
Hi Mischa,

every now-and-then a developer forgets to call cy.initializeNgApimock() within our automated E2E tests. This quite often results in flaky tests, because sometimes the default mocks remain to be returned by ngapimock even though a selectPreset/selectScenario has been called. 

I was looking into the code and had begun to implement a check for the ngapimockid to be set. But began to wonder why this initialization is not automatically done. Is there any reason why it would be desired to use this plugin without the ngapimockid to be set?

It could be as simple as:
```
invoke(query: string, method: string, body: any): Cypress.Chainable<any> {
        this.setNgApimockCookie();
        ....
}
```

If you agree, i could provide you with a PR for this...

groetjes, Sander

**Comment by GrumpyMeow** [comment]
@mdasberg ?

**Comment by mdasberg** [comment]
@GrumpyMeow There should always be a ngapimockId set. This ensures that your test can run in parallel.
The reason why I did it in an `cy.initializeNgApimock()` is so that you make sure that in you test you start a new session for a test. But that could be a separate step as well.
